### PR TITLE
expose QFileDevice to scripts

### PR DESCRIPTION
**Pull request by JulienMaille**

### CODE REVIEW

**Comment by JulienMaille** [comment]
I tried to understand why `QFile.write()` works with qt4 bindings but not qt5.
Since QFile now inherits from QFileDevice, I added this class to the bindings.
However I still can't call write() on a QFile

**Comment by qcad** [comment]
QFile::write has been exposed to scripts in the latest snapshot releases (>= 3.25.2.1).

For text based file IO, you can use QTextStream instead.

**Comment by JulienMaille** [comment]
Thank you for your reply. May I ask why it has too be fixed in `RScriptHandlerEcma.cpp` https://github.com/qcad/qcad/commit/57eb7a49cf9cd2ced01dd8631c859756c0c5f6e1 and not in qtscriptgenerator? Why doesn't it work out of the box like other inherited methods?

**Comment by qcad** [comment]
We generally prefer to add missing script bindings in RScriptHandlerEcma instead of the auto generated qtscriptgenerator code. qtscriptgenerator is no longer maintained by its creators.

**Pull request closed without merging**
